 Orig. Term: -561
       JSON: -561
Result Term: -561

 Orig. Term: 0
       JSON: 0
Result Term: 0

 Orig. Term: 561
       JSON: 561
Result Term: 561

 Orig. Term: 
       JSON: ""
Result Term: 

 Orig. Term: aaabbbccc
       JSON: "aaabbbccc"
Result Term: aaabbbccc

 Orig. Term: ûń
       JSON: "\u00FB\u0144"
Result Term: ûń

 Orig. Term: 3.141
       JSON: 3.141
Result Term: 3.141

 Orig. Term: infinity
       JSON: error: cannot convert non-finite float to JSON

 Orig. Term: A
       JSON: "A"
Result Term: A

 Orig. Term: no
       JSON: false
Result Term: no

 Orig. Term: yes
       JSON: true
Result Term: yes

 Orig. Term: 2365712637126347861237846728356712647827834723847812937812734871293478127
       JSON: "2365712637126347861237846728356712647827834723847812937812734871293478127"
Result Term: 2365712637126347861237846728356712647827834723847812937812734871293478127

 Orig. Term: 2000-02-18 19:30:00
       JSON: "2000-02-18 19:30:00"
Result Term: 2000-02-18 19:30:00

 Orig. Term: 2013-03-02 20:30:11.000123
       JSON: "2013-03-02 20:30:11.000123"
Result Term: 2013-03-02 20:30:11.000123

 Orig. Term: P0D
       JSON: "P0D"
Result Term: P0D

 Orig. Term: [1, 2, 3]
       JSON: [1,2,3]
Result Term: [1, 2, 3]

 Orig. Term: apple
       JSON: "apple"
Result Term: apple

 Orig. Term: pear
       JSON: "pear"
Result Term: pear

 Orig. Term: [apple, orange, lemon, pear]
       JSON: ["apple","orange","lemon","pear"]
Result Term: [apple, orange, lemon, pear]

 Orig. Term: yes("foo")
       JSON: "foo"
Result Term: yes("foo")

 Orig. Term: no
       JSON: null
Result Term: no

 Orig. Term: apple - orange
       JSON: {"fst":"apple","snd":"orange"}
Result Term: apple - orange

 Orig. Term: [1, 2, 3] - [apple, orange, pear]
       JSON: {"fst":[1,2,3],"snd":["apple","orange","pear"]}
Result Term: [1, 2, 3] - [apple, orange, pear]

 Orig. Term: sol([1, 2, 3, 4])
       JSON: [1,2,3,4]
Result Term: sol([1, 2, 3, 4])

 Orig. Term: sul([1, 1, 2, 2, 3, 3, 4, 4])
       JSON: [1,2,3,4]
Result Term: sul([4, 3, 2, 1])

 Orig. Term: two(3, three(1, 2, empty, empty, empty), two(4, empty, empty))
       JSON: [1,2,3,4]
Result Term: two(3, three(1, 2, empty, empty, empty), two(4, empty, empty))

 Orig. Term: ct(4, two(2, two(1, empty, empty), three(3, 4, empty, empty, empty)))
       JSON: [1,2,3,4]
Result Term: ct(4, two(3, three(1, 2, empty, empty, empty), two(4, empty, empty)))

 Orig. Term: tree(2, 4, tree(1, 1, empty, empty), tree(3, 2, empty, tree(4, 1, empty, empty)))
       JSON: [1,2,3,4]
Result Term: tree(3, 4, tree(2, 2, tree(1, 1, empty, empty), empty), tree(4, 1, empty, empty))

 Orig. Term: [apple - "Apple", orange - "Orange", lemon - "Lemon"]
       JSON: [{"fst":"apple","snd":"Apple"},{"fst":"orange","snd":"Orange"},{"fst":"lemon","snd":"Lemon"}]
Result Term: [apple - "Apple", orange - "Orange", lemon - "Lemon"]

 Orig. Term: four(apple, "Apple", orange, "Orange", lemon, "Lemon", empty, empty, empty, empty)
       JSON: [{"fst":"apple","snd":"Apple"},{"fst":"orange","snd":"Orange"},{"fst":"lemon","snd":"Lemon"}]
Result Term: four(apple, "Apple", orange, "Orange", lemon, "Lemon", empty, empty, empty, empty)

 Orig. Term: black(orange, "Orange", red(apple, "Apple2", black(apple, "Apple3", red(apple, "Apple4", empty, empty), empty), black(apple, "Apple", empty, empty)), black(lemon, "Lemon", empty, empty))
       JSON: [{"fst":"apple","snd":"Apple4"},{"fst":"apple","snd":"Apple3"},{"fst":"apple","snd":"Apple2"},{"fst":"apple","snd":"Apple"},{"fst":"orange","snd":"Orange"},{"fst":"lemon","snd":"Lemon"}]
Result Term: black(apple, "Apple3", black(apple, "Apple2", red(apple, "Apple", empty, empty), empty), black(orange, "Orange", red(apple, "Apple4", empty, empty), red(lemon, "Lemon", empty, empty)))

 Orig. Term: bimap(four(apple, "Apple", orange, "Orange", lemon, "Lemon", empty, empty, empty, empty), four("Apple", apple, "Lemon", lemon, "Orange", orange, empty, empty, empty, empty))
       JSON: [{"fst":"apple","snd":"Apple"},{"fst":"orange","snd":"Orange"},{"fst":"lemon","snd":"Lemon"}]
Result Term: bimap(four(apple, "Apple", orange, "Orange", lemon, "Lemon", empty, empty, empty, empty), four("Apple", apple, "Lemon", lemon, "Orange", orange, empty, empty, empty, empty))

 Orig. Term: nonempty_cord(branch_node(list_node(1, [2, 3]), list_node(5, [6, 7])))
       JSON: [1,2,3,5,6,7]
Result Term: nonempty_cord(list_node(1, [2, 3, 5, 6, 7]))

 Orig. Term: array([])
       JSON: []
Result Term: array([])

 Orig. Term: array([pear, lemon, lemon, orange, apple])
       JSON: ["pear","lemon","lemon","orange","apple"]
Result Term: array([pear, lemon, lemon, orange, apple])

 Orig. Term: array2d(0, 0, array([]))
       JSON: []
Result Term: array2d(0, 0, array([]))

 Orig. Term: array2d(3, 3, array([apple, pear, apple, orange, apple, pear, pear, apple, orange]))
       JSON: [["apple","pear","apple"],["orange","apple","pear"],["pear","apple","orange"]]
Result Term: array2d(3, 3, array([apple, pear, apple, orange, apple, pear, pear, apple, orange]))

 Orig. Term: version_array([])
       JSON: []
Result Term: version_array([])

 Orig. Term: version_array([pear, lemon, lemon, orange, apple])
       JSON: ["pear","lemon","lemon","orange","apple"]
Result Term: version_array([pear, lemon, lemon, orange, apple])

 Orig. Term: "<24:10AFBD>"
       JSON: "<24:10AFBD>"
Result Term: "<24:10AFBD>"

 Orig. Term: [unit, unit, unit]
       JSON: ["unit","unit","unit"]
Result Term: [unit, unit, unit]

 Orig. Term: queue([], [2, 3, 5, 7, 11, 13, 17, 19, 23])
       JSON: [2,3,5,7,11,13,17,19,23]
Result Term: queue([], [2, 3, 5, 7, 11, 13, 17, 19, 23])

 Orig. Term: [bool(yes), bool(no), null, number(5.61)]
       JSON: [true,false,null,5.61]
Result Term: [bool(yes), bool(no), null, number(5.61)]

 Orig. Term: pointer(["foo", "/bar", "12", "-", "~~~/"])
       JSON: "\/foo\/~1bar\/12\/-\/~0~0~0~1"
Result Term: pointer(["foo", "/bar", "12", "-", "~~~/"])

to_string(null) = "null"
to_string(bool(no)) = "false"
to_string(bool(yes)) = "true"
to_string(number(0.0)) = "0"
to_string(number(-3.141)) = "-3.141"
to_string(number(3.141)) = "3.141"
to_string(string("")) = """"
to_string(string("foo")) = ""foo""
to_string(array([])) = "[]"
to_string(array([null, bool(yes), number(1.0), array([number(1.0)])])) = "[null,true,1,[1]]"
to_string(object(empty)) = "{}"
to_string(object(four("baaz", number(5.3), "bar", bool(yes), "foo", null, empty, empty, empty, empty))) = "{"baaz":5.3,"bar":true,"foo":null}"

from_string("null") = null
from_string("true") = bool(yes)
from_string("false") = bool(no)
from_string("3e2") = number(300.0)
from_string("3E2") = number(300.0)
from_string("3.141") = number(3.141)
from_string("0.0") = number(0.0)
from_string("-3.141") = number(-3.141)
from_string("-3e2") = number(-300.0)
from_string("-3E2") = number(-300.0)
from_string(""foo"") = string("foo")
from_string("   null") = null
from_string("[]") = array([])
from_string("[1.0, 2.0, 3.0]") = array([number(1.0), number(2.0), number(3.0)])
from_string("[null, true, 3.0]") = array([null, bool(yes), number(3.0)])
from_string("{}") = object(empty)
from_string("{"foo" : 3.0}") = object(two("foo", number(3.0), empty, empty))
from_string("{"foo" : -3e2}") = object(two("foo", number(-300.0), empty, empty))
from_string("{"foo" : true, "bar" : false}") = object(three("bar", bool(no), "foo", bool(yes), empty, empty, empty))

from_string("Null") <<FALSE>>
from_string("12.") <<FALSE>>
from_string("12e") <<FALSE>>
from_string("12E") <<FALSE>>
from_string(".12") <<FALSE>>
from_string("[1.0, 2.0") <<FALSE>>
from_string("{"foo" : }") <<FALSE>>
from_string("{}{}") <<FALSE>>
from_string("[1, 2, 3][") <<FALSE>>
from_string("[1, 2, 3]]") <<FALSE>>
from_string("nullnull") <<FALSE>>
from_string("true 1.23") <<FALSE>>
from_string("{ "a" : 12.3 } true") <<FALSE>>
