*** Testing get/4 method (values.json_stream) ***

null
true
false
1.23
500
"Hello"
""
[
  false,
  true,
  false
]
{}
{
  "name" : null
}
{
  "name1" : true,
  "name2" : false
}
[
  {},
  {},
  {}
]

*** Testing get/4 method (bad_values.json_stream) ***

null
true
false
error: bad_values.json_stream:4:2: syntax error at '[': object member name not a string

*** Testing get_value/4 predicate (values.json_stream) ***

null
true
false
1.23
500
"Hello"
""
[
  false,
  true,
  false
]
{}
{
  "name" : null
}
{
  "name1" : true,
  "name2" : false
}
[
  {},
  {},
  {}
]

*** Testing get_value/4 predicate (bad_values.json_stream) ***

null
true
false
error: bad_values.json_stream:4:2: syntax error at '[': object member name not a string

*** Testing get_object/4 predicate (objects.json_stream) ***

{}
{}
{
  "foo" : 1
}
{
  "baaz" : false,
  "bar" : null
}

*** Testing get_object/4 predicate (bad_objects.json_stream) ***

error: bad_objects.json_stream:1:1: error: unexpected array value: value must be an object

*** Testing get_array/4 predicate (arrays.json_stream) ***

[]
[]
[]
[
  [],
  [],
  []
]
[
  1,
  2,
  3,
  4
]
[
  {},
  {},
  {
    "foo" : null
  }
]

*** Testing get_array/4 predicate (bad_arrays.json_stream) ***

[
  1,
  2,
  3
]
error: bad_arrays.json_stream:2:1: error: unexpected object value: value must be an array
