JSON: null
TYPE: int
RESULT: ERROR: at root: conversion to int failed: expected number, have null

JSON: "Hello"
TYPE: int
RESULT: ERROR: at root: conversion to int failed: expected number, have string

JSON: infinity
TYPE: int
RESULT: ERROR: at root: conversion to int failed: non-finite number

JSON: null
TYPE: int8
RESULT: ERROR: at root: conversion to int8 failed: expected number, have null

JSON: "Hello"
TYPE: int8
RESULT: ERROR: at root: conversion to int8 failed: expected number, have string

JSON: infinity
TYPE: int8
RESULT: ERROR: at root: conversion to int8 failed: non-finite number

JSON: -129
TYPE: int8
RESULT: ERROR: at root: conversion to int8 failed: number is out-of-bounds for type

JSON: -128
TYPE: int8
RESULT: OK: -128

JSON: 0
TYPE: int8
RESULT: OK: 0

JSON: 127
TYPE: int8
RESULT: OK: 127

JSON: 128
TYPE: int8
RESULT: ERROR: at root: conversion to int8 failed: number is out-of-bounds for type

JSON: [-1,0,1]
TYPE: list.list(int8)
RESULT: OK: [-1i8, 0i8, 1i8]

JSON: null
TYPE: int16
RESULT: ERROR: at root: conversion to int16 failed: expected number, have null

JSON: "Hello"
TYPE: int16
RESULT: ERROR: at root: conversion to int16 failed: expected number, have string

JSON: infinity
TYPE: int16
RESULT: ERROR: at root: conversion to int16 failed: non-finite number

JSON: -32769
TYPE: int16
RESULT: ERROR: at root: conversion to int16 failed: number is out-of-bounds for type

JSON: -32768
TYPE: int16
RESULT: OK: -32768

JSON: 32767
TYPE: int16
RESULT: OK: 32767

JSON: 32768
TYPE: int16
RESULT: ERROR: at root: conversion to int16 failed: number is out-of-bounds for type

JSON: [-1,0,1]
TYPE: list.list(int16)
RESULT: OK: [-1i16, 0i16, 1i16]

JSON: null
TYPE: int32
RESULT: ERROR: at root: conversion to int32 failed: expected number, have null

JSON: "Hello"
TYPE: int32
RESULT: ERROR: at root: conversion to int32 failed: expected number, have string

JSON: infinity
TYPE: int32
RESULT: ERROR: at root: conversion to int32 failed: non-finite number

JSON: -2147483649
TYPE: int32
RESULT: ERROR: at root: conversion to int32 failed: number is out-of-bounds for type

JSON: -2147483648
TYPE: int32
RESULT: OK: -2147483648

JSON: 2147483647
TYPE: int32
RESULT: OK: 2147483647

JSON: 2147483648
TYPE: int32
RESULT: ERROR: at root: conversion to int32 failed: number is out-of-bounds for type

JSON: [-1,0,1]
TYPE: list.list(int32)
RESULT: OK: [-1i32, 0i32, 1i32]

JSON: null
TYPE: int64
RESULT: ERROR: at root: conversion to int64 failed: expected string, have null

JSON: 561
TYPE: int64
RESULT: ERROR: at root: conversion to int64 failed: expected string, have number

JSON: "Hello"
TYPE: int64
RESULT: ERROR: at root: conversion to int64 failed: cannot convert string to integer

JSON: "-9223372036854775809"
TYPE: int64
RESULT: ERROR: at root: conversion to int64 failed: number is out-of-bounds for type

JSON: "-9223372036854775808"
TYPE: int64
RESULT: OK: -9223372036854775808

JSON: "9223372036854775807"
TYPE: int64
RESULT: OK: 9223372036854775807

JSON: "9223372036854775808"
TYPE: int64
RESULT: ERROR: at root: conversion to int64 failed: number is out-of-bounds for type

JSON: ["-1","0","1"]
TYPE: list.list(int64)
RESULT: OK: [-1i64, 0i64, 1i64]

JSON: null
TYPE: uint8
RESULT: ERROR: at root: conversion to uint8 failed: expected number, have null

JSON: "Hello"
TYPE: uint8
RESULT: ERROR: at root: conversion to uint8 failed: expected number, have string

JSON: infinity
TYPE: uint8
RESULT: ERROR: at root: conversion to uint8 failed: non-finite number

JSON: -1
TYPE: uint8
RESULT: ERROR: at root: conversion to uint8 failed: number is out-of-bounds for type

JSON: 0
TYPE: uint8
RESULT: OK: 0

JSON: 255
TYPE: uint8
RESULT: OK: 255

JSON: 256
TYPE: uint8
RESULT: ERROR: at root: conversion to uint8 failed: number is out-of-bounds for type

JSON: [0,1,255]
TYPE: list.list(uint8)
RESULT: OK: [0u8, 1u8, 255u8]

JSON: null
TYPE: uint16
RESULT: ERROR: at root: conversion to uint16 failed: expected number, have null

JSON: "Hello"
TYPE: uint16
RESULT: ERROR: at root: conversion to uint16 failed: expected number, have string

JSON: infinity
TYPE: uint16
RESULT: ERROR: at root: conversion to uint16 failed: non-finite number

JSON: -1
TYPE: uint16
RESULT: ERROR: at root: conversion to uint16 failed: number is out-of-bounds for type

JSON: 0
TYPE: uint16
RESULT: OK: 0

JSON: 32767
TYPE: uint16
RESULT: OK: 32767

JSON: 32768
TYPE: uint16
RESULT: OK: 32768

JSON: [0,1,32768]
TYPE: list.list(uint16)
RESULT: OK: [0u16, 1u16, 32768u16]

JSON: null
TYPE: uint64
RESULT: ERROR: at root: conversion to uint64 failed: expected string, have null

JSON: 561
TYPE: uint64
RESULT: ERROR: at root: conversion to uint64 failed: expected string, have number

JSON: "Hello"
TYPE: uint64
RESULT: ERROR: at root: conversion to uint64 failed: cannot convert string to integer

JSON: "-1"
TYPE: uint64
RESULT: ERROR: at root: conversion to uint64 failed: number is out-of-bounds for type

JSON: "0"
TYPE: uint64
RESULT: OK: 0

JSON: "18446744073709551615"
TYPE: uint64
RESULT: OK: 18446744073709551615

JSON: "18446744073709551616"
TYPE: uint64
RESULT: ERROR: at root: conversion to uint64 failed: number is out-of-bounds for type

JSON: ["0","1"]
TYPE: list.list(uint64)
RESULT: OK: [0u64, 1u64]

JSON: null
TYPE: float
RESULT: ERROR: at root: conversion to float failed: expected number, have null

JSON: "5.61"
TYPE: float
RESULT: ERROR: at root: conversion to float failed: expected number, have string

JSON: infinity
TYPE: float
RESULT: ERROR: at root: conversion to float failed: non-finite number

JSON: null
TYPE: character
RESULT: ERROR: at root: conversion to character failed: expected string, have null

JSON: "AA"
TYPE: character
RESULT: ERROR: at root: conversion to character failed: has length 2, expected length 1

JSON: ""
TYPE: character
RESULT: ERROR: at root: conversion to character failed: has length 0, expected length 1

JSON: null
TYPE: string
RESULT: ERROR: at root: conversion to string failed: expected string, have null

JSON: 5.61
TYPE: string
RESULT: ERROR: at root: conversion to string failed: expected string, have number

JSON: []
TYPE: string
RESULT: ERROR: at root: conversion to string failed: expected string, have array

JSON: ""
TYPE: string
RESULT: OK: 

JSON: "Hello"
TYPE: string
RESULT: OK: Hello

JSON: null
TYPE: bool.bool
RESULT: ERROR: at root: conversion to bool.bool failed: expected Boolean, have null

JSON: "Hello"
TYPE: bool.bool
RESULT: ERROR: at root: conversion to bool.bool failed: expected Boolean, have string

JSON: 5.61
TYPE: bool.bool
RESULT: ERROR: at root: conversion to bool.bool failed: expected Boolean, have number

JSON: null
TYPE: integer.integer
RESULT: ERROR: at root: conversion to integer.integer failed: expected string, have null

JSON: "Hello"
TYPE: integer.integer
RESULT: ERROR: at root: conversion from string to integer.integer failed: have "Hello"

JSON: "12345678912345678912346"
TYPE: integer.integer
RESULT: OK: 12345678912345678912346

JSON: "-123456789123456789123456"
TYPE: integer.integer
RESULT: OK: -123456789123456789123456

JSON: null
TYPE: bitmap.bitmap
RESULT: ERROR: at root: conversion to bitmap.bitmap failed: expected string, have null

JSON: ""
TYPE: bitmap.bitmap
RESULT: ERROR: at root: conversion to bitmap.bitmap failed: unrecognised string: ""

JSON: "---"
TYPE: bitmap.bitmap
RESULT: ERROR: at root: conversion to bitmap.bitmap failed: unrecognised string: "---"

JSON: "<24:10AFBD>"
TYPE: bitmap.bitmap
RESULT: OK: "<24:10AFBD>"

JSON: null
TYPE: maybe.maybe(string)
RESULT: OK: no

JSON: {"yes":"FOO"}
TYPE: maybe.maybe(string)
RESULT: OK: yes("FOO")

JSON: "BAR"
TYPE: maybe.maybe(string)
RESULT: ERROR: at root: conversion to maybe.maybe(string) failed: expected object or null, have string

JSON: 561
TYPE: maybe.maybe(string)
RESULT: ERROR: at root: conversion to maybe.maybe(string) failed: expected object or null, have number

JSON: null
TYPE: maybe.maybe_error(string, string)
RESULT: ERROR: at root: conversion to maybe.maybe_error(string, string) failed: expected object, have null

JSON: {"ok":"FOO"}
TYPE: maybe.maybe_error(string, string)
RESULT: OK: ok("FOO")

JSON: {"error":"BAR"}
TYPE: maybe.maybe_error(string, string)
RESULT: OK: error("BAR")

JSON: {"field1":"A","field2":"B"}
TYPE: maybe.maybe_error(string, string)
RESULT: ERROR: at root: conversion to maybe.maybe_error(string, string) failed: object is not a maybe_error/2 value

JSON: {"error":"BAR","ok":"FOO"}
TYPE: maybe.maybe_error(string, string)
RESULT: ERROR: at root: conversion to maybe.maybe_error(string, string) failed: object cannot have both "ok" and  "error" members

JSON: null
TYPE: list.list(int)
RESULT: ERROR: at root: conversion to list.list(int) failed: expected array, have null

JSON: []
TYPE: list.list(int)
RESULT: OK: []

JSON: [1]
TYPE: list.list(int)
RESULT: OK: [1]

JSON: [1,2]
TYPE: list.list(int)
RESULT: OK: [1, 2]

JSON: [10,null]
TYPE: list.list(int)
RESULT: ERROR: at /1: conversion to int failed: expected number, have null

JSON: null
TYPE: array.array(int)
RESULT: ERROR: at root: conversion to array.array(int) failed: expected array, have null

JSON: null
TYPE: array2d.array2d(int)
RESULT: ERROR: at root: conversion to array2d.array2d(int) failed: expected array, have null

JSON: []
TYPE: array2d.array2d(int)
RESULT: OK: array2d(0, 0, array([]))

JSON: [[],[]]
TYPE: array2d.array2d(int)
RESULT: OK: array2d(2, 0, array([]))

JSON: [[],null]
TYPE: array2d.array2d(int)
RESULT: ERROR: at root: conversion to array2d.array2d(int) failed:  row 1 is null, expected array

JSON: [[],[3]]
TYPE: array2d.array2d(int)
RESULT: ERROR: at root: conversion to array2d.array2d(int) failed: row 0 has length 0, row 1 has length 1

JSON: [false,[3]]
TYPE: array2d.array2d(int)
RESULT: ERROR: at /0: conversion to array2d.array2d(int) failed: expected array, have Boolean

JSON: [[1,2,3],[4,5,6],[7,8,9]]
TYPE: array2d.array2d(int)
RESULT: OK: array2d(3, 3, array([1, 2, 3, 4, 5, 6, 7, 8, 9]))

JSON: [[1],[2,3]]
TYPE: array2d.array2d(int)
RESULT: ERROR: at /1: conversion to array2d.array2d(int) failed: row 1 has length 2, expected length 1

JSON: [[1,2,3],true,[7,8,9]]
TYPE: array2d.array2d(int)
RESULT: ERROR: at root: conversion to array2d.array2d(int) failed: expected array, have Boolean

JSON: [[1,2,3],[4,null,6],[7,8,9]]
TYPE: array2d.array2d(int)
RESULT: ERROR: at /1/1: conversion to int failed: expected number, have null

JSON: {"edges":[],"vertices":[]}
TYPE: digraph.digraph(string)
RESULT: OK: digraph(0u, bimap(empty, empty), empty, empty)

JSON: {"edges":[{"dest":"A","source":"C"}],"vertices":["A","B"]}
TYPE: digraph.digraph(string)
RESULT: ERROR: at /edges/0/source: conversion to digraph.digraph(string) failed: '"C"' is not in vertex set

JSON: {"edges":[{"dest":"C","source":"A"}],"vertices":["A","B"]}
TYPE: digraph.digraph(string)
RESULT: ERROR: at /edges/0/dest: conversion to digraph.digraph(string) failed: '"C"' is not in vertex set

JSON: {"vertices":["A","B"]}
TYPE: digraph.digraph(string)
RESULT: ERROR: at root: conversion to digraph.digraph(string) failed: object has no member named "edges"

JSON: {"edges":[{"dest":"C","source":"A"}]}
TYPE: digraph.digraph(string)
RESULT: ERROR: at root: conversion to digraph.digraph(string) failed: object has no member named "vertices"

JSON: null
TYPE: digraph.digraph(string)
RESULT: ERROR: at root: conversion to digraph.digraph(string) failed: expected object, have null

JSON: {"edges":[],"vertices":[null,"B"]}
TYPE: digraph.digraph(string)
RESULT: ERROR: at /vertices/0: conversion to string failed: expected string, have null

JSON: []
TYPE: tree234.tree234(int, int)
RESULT: OK: empty

JSON: {"bar":["c"],"foo":["a","b"]}
TYPE: tree234.tree234(string, list.list(string))
RESULT: ERROR: at root: conversion to tree234.tree234(string, list.list(string)) failed: expected array, have object

JSON: []
TYPE: bimap.bimap(int, int)
RESULT: OK: bimap(empty, empty)

JSON: {"bar":["c"],"foo":["a","b"]}
TYPE: bimap.bimap(string, list.list(string))
RESULT: ERROR: at root: conversion to bimap.bimap(string, list.list(string)) failed: expected array, have object

JSON: []
TYPE: rbtree.rbtree(int, int)
RESULT: OK: empty

JSON: {"bar":["c"],"foo":["a","b"]}
TYPE: rbtree.rbtree(string, list.list(string))
RESULT: ERROR: at root: conversion to rbtree.rbtree(string, list.list(string)) failed: expected array, have object

JSON: []
TYPE: one_or_more.one_or_more(string)
RESULT: ERROR: at root: conversion to one_or_more.one_or_more(string) failed: expected non-empty array

JSON: ["a"]
TYPE: one_or_more.one_or_more(string)
RESULT: OK: one_or_more("a", [])

JSON: ["a","b","c"]
TYPE: one_or_more.one_or_more(string)
RESULT: OK: one_or_more("a", ["b", "c"])

JSON: []
TYPE: set_bbbtree.set_bbbtree(string)
RESULT: OK: empty

JSON: ["a"]
TYPE: set_bbbtree.set_bbbtree(string)
RESULT: OK: tree("a", 1, empty, empty)

JSON: ["a","b","a"]
TYPE: set_bbbtree.set_bbbtree(string)
RESULT: OK: tree("a", 2, empty, tree("b", 1, empty, empty))

JSON: 561
TYPE: set_bbbtree.set_bbbtree(string)
RESULT: ERROR: at root: conversion to set_bbbtree.set_bbbtree(string) failed: expected array, have number

JSON: ["a",720]
TYPE: set_bbbtree.set_bbbtree(string)
RESULT: ERROR: at /1: conversion to string failed: expected string, have number

JSON: []
TYPE: set_ordlist.set_ordlist(string)
RESULT: OK: sol([])

JSON: ["a"]
TYPE: set_ordlist.set_ordlist(string)
RESULT: OK: sol(["a"])

JSON: ["a","b","a"]
TYPE: set_ordlist.set_ordlist(string)
RESULT: OK: sol(["a", "b"])

JSON: 561
TYPE: set_ordlist.set_ordlist(string)
RESULT: ERROR: at root: conversion to set_ordlist.set_ordlist(string) failed: expected array, have number

JSON: ["a",720]
TYPE: set_ordlist.set_ordlist(string)
RESULT: ERROR: at /1: conversion to string failed: expected string, have number

JSON: []
TYPE: set_unordlist.set_unordlist(string)
RESULT: OK: sul([])

JSON: ["a"]
TYPE: set_unordlist.set_unordlist(string)
RESULT: OK: sul(["a"])

JSON: ["a","b","a"]
TYPE: set_unordlist.set_unordlist(string)
RESULT: OK: sul(["a", "b", "a"])

JSON: 561
TYPE: set_unordlist.set_unordlist(string)
RESULT: ERROR: at root: conversion to set_unordlist.set_unordlist(string) failed: expected array, have number

JSON: ["a",720]
TYPE: set_unordlist.set_unordlist(string)
RESULT: ERROR: at /1: conversion to string failed: expected string, have number

JSON: []
TYPE: set_ctree234.set_ctree234(string)
RESULT: OK: ct(0, empty)

JSON: ["a"]
TYPE: set_ctree234.set_ctree234(string)
RESULT: OK: ct(1, two("a", empty, empty))

JSON: ["a","b","a"]
TYPE: set_ctree234.set_ctree234(string)
RESULT: OK: ct(2, three("a", "b", empty, empty, empty))

JSON: 561
TYPE: set_ctree234.set_ctree234(string)
RESULT: ERROR: at root: conversion to set_ctree234.set_ctree234(string) failed: expected array, have number

JSON: ["a",720]
TYPE: set_ctree234.set_ctree234(string)
RESULT: ERROR: at /1: conversion to string failed: expected string, have number

JSON: []
TYPE: set_tree234.set_tree234(string)
RESULT: OK: empty

JSON: ["a"]
TYPE: set_tree234.set_tree234(string)
RESULT: OK: two("a", empty, empty)

JSON: ["a","b","a"]
TYPE: set_tree234.set_tree234(string)
RESULT: OK: three("a", "b", empty, empty, empty)

JSON: 561
TYPE: set_tree234.set_tree234(string)
RESULT: ERROR: at root: conversion to set_tree234.set_tree234(string) failed: expected array, have number

JSON: ["a",720]
TYPE: set_tree234.set_tree234(string)
RESULT: ERROR: at /1: conversion to string failed: expected string, have number

